[package]
name = "iroha_stable"

edition = "2021"
version = "0.1.0"
# TODO: Add authors, then reference from all workspace crates
# authors = []

license = "Apache-2.0"

[dependencies]
iroha_wasm_builder = { git = "https://github.com/hyperledger/iroha", tag = "v2.0.0-pre-rc.22.0" }
iroha = { git = "https://github.com/hyperledger/iroha/", tag = "v2.0.0-pre-rc.22.0" }
bonds_data_model = { path = "smart_contracts/data_model" }

eyre = "0.6.12"
