[package]
name = "bond_maturation"

edition.workspace = true
version.workspace = true

license.workspace = true

[lib]
crate-type = ['cdylib']

[dependencies]
bonds_data_model.workspace = true
iroha_trigger.workspace = true

panic-halt.workspace = true
getrandom.workspace = true
dlmalloc.workspace = true
