[package]
name = "register_bond"

edition.workspace = true
version.workspace = true

license.workspace = true

[lib]
crate-type = ['cdylib']

[dependencies]
bonds_data_model.workspace = true
iroha_trigger.workspace = true

panic-halt.workspace = true
getrandom.workspace = true
dlmalloc.workspace = true

[build-dependencies]
iroha_wasm_builder = { git = "https://github.com/hyperledger/iroha", tag = "v2.0.0-pre-rc.22.0" }
