[package]
name = "bonds_data_model"

edition.workspace = true
version.workspace = true

license.workspace = true

[dependencies]
iroha_data_model = { git = "https://github.com/hyperledger/iroha", tag = "v2.0.0-pre-rc.22.0", default-features = false }

serde_json.workspace = true
serde.workspace = true
